stages:
  - build

job_build:
  stage: build
  only:
    - main
  # 缓存 node_modules
  cache:
    paths:
      - node_modules/
  script:
    - echo "$LOCAL_REGISTRY"
    - echo "$LOCAL_PUBLISH_REGISTRY"
    - echo "$LOCAL_REGISTRY_AUTH_TOKEN"
    - echo "$LOCAL_REGISTRY_EMAIL"
    - npm set registry "$LOCAL_REGISTRY"
    - echo "always-auth = true" > ~/.npmrc
    - echo "email = ${LOCAL_REGISTRY_EMAIL}" > ~/.npmrc
    - echo "_auth = ${LOCAL_REGISTRY_AUTH_TOKEN}" > ~/.npmrc
    - yarn install
    - yarn run test
    - yarn run lib
    - yarn publish --registry "$LOCAL_PUBLISH_REGISTRY"
    - yarn run docs:build --dest public
  artifacts:
    paths:
      - public
  tags:
    - publish