stages:
  - build

job_build:
  stage: build
  only:
    - main
  script:
    - echo "$LOCAL_REGISTRY"
    - echo "$LOCAL_PUBLISH_REGISTRY"
    - echo "$LOCAL_REGISTRY_AUTH_TOKEN"
    - echo "$LOCAL_REGISTRY_EMAIL"
    - npm set registry "$LOCAL_REGISTRY"
    - echo "always-auth = true" > ~/.npmrc
    - echo "email = ${LOCAL_REGISTRY_EMAIL}" > ~/.npmrc
    - echo "_auth = ${LOCAL_REGISTRY_AUTH_TOKEN}" > ~/.npmrc
    - yarn install
    - yarn run test
    - yarn run lib
    - yarn publish --registry "$LOCAL_PUBLISH_REGISTRY"
  tags:
    - publish

pages:
  # 每当 push 到 main 分支时触发部署
  only:
    - main

  # 缓存 node_modules
  cache:
    paths:
      - node_modules/

  # 安装依赖并运行构建脚本
  script:
    - yarn install --frozen-lockfile
    - yarn run test
    - yarn run lib
    - yarn run docs:build --dest public

  artifacts:
    paths:
      - public