stages:
  - build

job_build:
  stage: build
  only:
    - main
  script:
    - echo "$LOCAL_REGISTRY"
    - echo "$LOCAL_REGISTRY_AUTH_TOKEN"
    - echo "$LOCAL_REGISTRY_EMAIL"
    - yarn install
    - yarn run test
    - yarn run lib
  tags:
    - publish