<template><h1 id="表格初始化数据" tabindex="-1"><a class="header-anchor" href="#表格初始化数据" aria-hidden="true">#</a> 表格初始化数据</h1>
<h2 id="默认数据类型初始化" tabindex="-1"><a class="header-anchor" href="#默认数据类型初始化" aria-hidden="true">#</a> 默认数据类型初始化</h2>
<vma-grid :data="gridData"
    :minDimensions="[10, 10]"
    resizeColumn
    resizeRow
    style="height: 400px;">
</vma-grid>
<p>:::: code-group</p>
<p>::: code-group-item ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code>data<span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">{</span>r<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> c<span class="token operator">:</span> <span class="token number">2</span><span class="token punctuation">,</span> name<span class="token operator">:</span> <span class="token string">'B1'</span><span class="token punctuation">,</span> v<span class="token operator">:</span> <span class="token string">'35'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span>r<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> c<span class="token operator">:</span> <span class="token number">3</span><span class="token punctuation">,</span> name<span class="token operator">:</span> <span class="token string">'C1'</span><span class="token punctuation">,</span> v<span class="token operator">:</span> <span class="token string">'=3 / 6'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span>r<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> c<span class="token operator">:</span> <span class="token number">4</span><span class="token punctuation">,</span> name<span class="token operator">:</span> <span class="token string">'D1'</span><span class="token punctuation">,</span> v<span class="token operator">:</span> <span class="token string">'= 1 - EXP(C1 ^ 3)'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">{</span>r<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> c<span class="token operator">:</span> <span class="token number">5</span><span class="token punctuation">,</span> name<span class="token operator">:</span> <span class="token string">'E1'</span><span class="token punctuation">,</span> v<span class="token operator">:</span> <span class="token string">'=D1 + 3'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>:::</p>
<p>::::</p>
<h2 id="二维数组形式的表格数据类型初始化" tabindex="-1"><a class="header-anchor" href="#二维数组形式的表格数据类型初始化" aria-hidden="true">#</a> 二维数组形式的表格数据类型初始化</h2>
<h3 id="常规二维数组数据" tabindex="-1"><a class="header-anchor" href="#常规二维数组数据" aria-hidden="true">#</a> 常规二维数组数据</h3>
<vma-grid :data="gridTableTypeData"
    :minDimensions="[10, 10]"
    resizeColumn
    resizeRow
    style="height: 400px;">
</vma-grid>
<p>:::: code-group</p>
<p>::: code-group-item ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code>dataType<span class="token operator">:</span> <span class="token string">'table'</span>
data<span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token number">20111120001</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token string">'1001'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A1 , B1 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A1 , C1 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三1 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120002</span><span class="token punctuation">,</span> <span class="token number">102</span><span class="token punctuation">,</span> <span class="token string">'1002'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A2 , B2 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A2 , C2 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三2 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120003</span><span class="token punctuation">,</span> <span class="token number">103</span><span class="token punctuation">,</span> <span class="token string">'1003'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A3 , B3 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A3 , C3 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三3 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120004</span><span class="token punctuation">,</span> <span class="token number">104</span><span class="token punctuation">,</span> <span class="token string">'1004'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A4 , B4 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A4 , C4 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三4 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120005</span><span class="token punctuation">,</span> <span class="token number">105</span><span class="token punctuation">,</span> <span class="token string">'1005'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A5 , B5 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A5 , C5 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三5 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120006</span><span class="token punctuation">,</span> <span class="token number">106</span><span class="token punctuation">,</span> <span class="token string">'1006'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A6 , B6 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A6 , C6 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三6 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120007</span><span class="token punctuation">,</span> <span class="token number">107</span><span class="token punctuation">,</span> <span class="token string">'1007'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A7 , B7 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A7 , C7 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三7 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120008</span><span class="token punctuation">,</span> <span class="token number">108</span><span class="token punctuation">,</span> <span class="token string">'1008'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A8 , B8 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A8 , C8 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三8 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120009</span><span class="token punctuation">,</span> <span class="token number">109</span><span class="token punctuation">,</span> <span class="token string">'1009'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A9 , B9 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A9 , C9 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三9 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120010</span><span class="token punctuation">,</span> <span class="token number">110</span><span class="token punctuation">,</span> <span class="token string">'1010'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A10: B10)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A10: C10)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三10'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120011</span><span class="token punctuation">,</span> <span class="token number">111</span><span class="token punctuation">,</span> <span class="token string">'1011'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A11: B11)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A11: C11)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三11'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120012</span><span class="token punctuation">,</span> <span class="token number">112</span><span class="token punctuation">,</span> <span class="token string">'1012'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A12: B12)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A12: C12)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三12'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120013</span><span class="token punctuation">,</span> <span class="token number">113</span><span class="token punctuation">,</span> <span class="token string">'1013'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A13: B13)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A13: C13)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三13'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120014</span><span class="token punctuation">,</span> <span class="token number">114</span><span class="token punctuation">,</span> <span class="token string">'1014'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A14: B14)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A14: C14)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三14'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120015</span><span class="token punctuation">,</span> <span class="token number">115</span><span class="token punctuation">,</span> <span class="token string">'1015'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A15: B15)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A15: C15)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三15'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120016</span><span class="token punctuation">,</span> <span class="token number">116</span><span class="token punctuation">,</span> <span class="token string">'1016'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A16: B16)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A16: C16)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三16'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120017</span><span class="token punctuation">,</span> <span class="token number">117</span><span class="token punctuation">,</span> <span class="token string">'1017'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A17: B17)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A17: C17)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三17'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120018</span><span class="token punctuation">,</span> <span class="token number">118</span><span class="token punctuation">,</span> <span class="token string">'1018'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A18: B18)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A18: C18)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三18'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120019</span><span class="token punctuation">,</span> <span class="token number">119</span><span class="token punctuation">,</span> <span class="token string">'1019'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A19: B19)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A19: C19)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三19'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120020</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token string">'1020'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A20: B20)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A20: C20)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三20'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120021</span><span class="token punctuation">,</span> <span class="token number">121</span><span class="token punctuation">,</span> <span class="token string">'1021'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A21, B21)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A21, C21)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三21'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120022</span><span class="token punctuation">,</span> <span class="token number">122</span><span class="token punctuation">,</span> <span class="token string">'1022'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A22, B22)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A22, C22)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三22'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120023</span><span class="token punctuation">,</span> <span class="token number">123</span><span class="token punctuation">,</span> <span class="token string">'1023'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A23, B23)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A23, C23)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三23'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120024</span><span class="token punctuation">,</span> <span class="token number">124</span><span class="token punctuation">,</span> <span class="token string">'1024'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A24, B24)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A24, C24)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三24'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120025</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token string">'1025'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A25, B25)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A25, C25)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三25'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120026</span><span class="token punctuation">,</span> <span class="token number">126</span><span class="token punctuation">,</span> <span class="token string">'1026'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A26, B26)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A26, C26)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三26'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120027</span><span class="token punctuation">,</span> <span class="token number">127</span><span class="token punctuation">,</span> <span class="token string">'1027'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A27, B27)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A27, C27)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三27'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120028</span><span class="token punctuation">,</span> <span class="token number">128</span><span class="token punctuation">,</span> <span class="token string">'1028'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A28, B28)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A28, C28)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三28'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120029</span><span class="token punctuation">,</span> <span class="token number">129</span><span class="token punctuation">,</span> <span class="token string">'1029'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A29, B29)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A29, C29)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三29'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120030</span><span class="token punctuation">,</span> <span class="token number">130</span><span class="token punctuation">,</span> <span class="token string">'1030'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A30, B30)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A30, C30)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三30'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>:::</p>
<p>::::</p>
<h3 id="包含对象的二维数组数据" tabindex="-1"><a class="header-anchor" href="#包含对象的二维数组数据" aria-hidden="true">#</a> 包含对象的二维数组数据</h3>
<vma-grid :data="gridAdvancedTableTypeData"
    :minDimensions="[10, 10]"
    resizeColumn
    resizeRow
    style="height: 400px;">
</vma-grid>
<p>:::: code-group</p>
<p>::: code-group-item ts</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code>dataType<span class="token operator">:</span> <span class="token string">'table'</span>
data<span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token number">20111120001</span><span class="token punctuation">,</span> <span class="token number">101</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>v<span class="token operator">:</span> <span class="token string">'1001'</span><span class="token punctuation">,</span> it<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> bl<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span> bg<span class="token operator">:</span> <span class="token string">'#0071be'</span><span class="token punctuation">,</span> fc<span class="token operator">:</span> <span class="token string">'#f2f2f2'</span><span class="token punctuation">,</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A1 , B1 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A1 , C1 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三1 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120002</span><span class="token punctuation">,</span> <span class="token number">102</span><span class="token punctuation">,</span> <span class="token string">'1002'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A2 , B2 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A2 , C2 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三2 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120003</span><span class="token punctuation">,</span> <span class="token number">103</span><span class="token punctuation">,</span> <span class="token string">'1003'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A3 , B3 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A3 , C3 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三3 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120004</span><span class="token punctuation">,</span> <span class="token number">104</span><span class="token punctuation">,</span> <span class="token string">'1004'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A4 , B4 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A4 , C4 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三4 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120005</span><span class="token punctuation">,</span> <span class="token number">105</span><span class="token punctuation">,</span> <span class="token string">'1005'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A5 , B5 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A5 , C5 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三5 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120006</span><span class="token punctuation">,</span> <span class="token number">106</span><span class="token punctuation">,</span> <span class="token string">'1006'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A6 , B6 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A6 , C6 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三6 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120007</span><span class="token punctuation">,</span> <span class="token number">107</span><span class="token punctuation">,</span> <span class="token string">'1007'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A7 , B7 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A7 , C7 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三7 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120008</span><span class="token punctuation">,</span> <span class="token number">108</span><span class="token punctuation">,</span> <span class="token string">'1008'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A8 , B8 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A8 , C8 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三8 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120009</span><span class="token punctuation">,</span> <span class="token number">109</span><span class="token punctuation">,</span> <span class="token string">'1009'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A9 , B9 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A9 , C9 )</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三9 '</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120010</span><span class="token punctuation">,</span> <span class="token number">110</span><span class="token punctuation">,</span> <span class="token string">'1010'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A10: B10)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A10: C10)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三10'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120011</span><span class="token punctuation">,</span> <span class="token number">111</span><span class="token punctuation">,</span> <span class="token string">'1011'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A11: B11)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A11: C11)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三11'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120012</span><span class="token punctuation">,</span> <span class="token number">112</span><span class="token punctuation">,</span> <span class="token string">'1012'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A12: B12)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A12: C12)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三12'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120013</span><span class="token punctuation">,</span> <span class="token number">113</span><span class="token punctuation">,</span> <span class="token string">'1013'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A13: B13)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A13: C13)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三13'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120014</span><span class="token punctuation">,</span> <span class="token number">114</span><span class="token punctuation">,</span> <span class="token string">'1014'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A14: B14)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A14: C14)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三14'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120015</span><span class="token punctuation">,</span> <span class="token number">115</span><span class="token punctuation">,</span> <span class="token string">'1015'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A15: B15)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A15: C15)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三15'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120016</span><span class="token punctuation">,</span> <span class="token number">116</span><span class="token punctuation">,</span> <span class="token string">'1016'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A16: B16)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A16: C16)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三16'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120017</span><span class="token punctuation">,</span> <span class="token number">117</span><span class="token punctuation">,</span> <span class="token string">'1017'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A17: B17)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A17: C17)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三17'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120018</span><span class="token punctuation">,</span> <span class="token number">118</span><span class="token punctuation">,</span> <span class="token string">'1018'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A18: B18)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A18: C18)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三18'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120019</span><span class="token punctuation">,</span> <span class="token number">119</span><span class="token punctuation">,</span> <span class="token string">'1019'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A19: B19)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A19: C19)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三19'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120020</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token string">'1020'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A20: B20)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A20: C20)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三20'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120021</span><span class="token punctuation">,</span> <span class="token number">121</span><span class="token punctuation">,</span> <span class="token string">'1021'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A21, B21)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A21, C21)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三21'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120022</span><span class="token punctuation">,</span> <span class="token number">122</span><span class="token punctuation">,</span> <span class="token string">'1022'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A22, B22)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A22, C22)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三22'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120023</span><span class="token punctuation">,</span> <span class="token number">123</span><span class="token punctuation">,</span> <span class="token string">'1023'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A23, B23)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A23, C23)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三23'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120024</span><span class="token punctuation">,</span> <span class="token number">124</span><span class="token punctuation">,</span> <span class="token string">'1024'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A24, B24)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A24, C24)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三24'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120025</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token string">'1025'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A25, B25)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A25, C25)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三25'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120026</span><span class="token punctuation">,</span> <span class="token number">126</span><span class="token punctuation">,</span> <span class="token string">'1026'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A26, B26)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A26, C26)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三26'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120027</span><span class="token punctuation">,</span> <span class="token number">127</span><span class="token punctuation">,</span> <span class="token string">'1027'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A27, B27)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A27, C27)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三27'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120028</span><span class="token punctuation">,</span> <span class="token number">128</span><span class="token punctuation">,</span> <span class="token string">'1028'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A28, B28)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A28, C28)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三28'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120029</span><span class="token punctuation">,</span> <span class="token number">129</span><span class="token punctuation">,</span> <span class="token string">'1029'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A29, B29)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A29, C29)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三29'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span><span class="token number">20111120030</span><span class="token punctuation">,</span> <span class="token number">130</span><span class="token punctuation">,</span> <span class="token string">'1030'</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A30, B30)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">=SUM(A30, C30)</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token string">'男/女'</span><span class="token punctuation">,</span> <span class="token string">'张三30'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token keyword">undefined</span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>:::</p>
<p>::::</p>
</template>

<script lang="ts">
import {defineComponent, reactive, ref} from 'vue';

export default defineComponent({
    name: 'GridInitDoc',
    setup() {
      const gridData = reactive([{
        name: 'sheet 1',
        r: 10,
        c: 10,
        status: 0,
        index: 0,
        order: 0,
        hide: 0,
        config: {},
        data: [
            {
                r: 1,
                c: 2,
                name: 'B1',
                v: '35'
            },
            {
                r: 1,
                c: 3,
                name: 'C1',
                v: '=3 / 6'
            },
            {
                r: 1,
                c: 4,
                name: 'D1',
                v: '= 1 - EXP(C1 ^ 3)'
            },
            {
                r: 1,
                c: 5,
                name: 'E1',
                v: '=D1 + 3'
            },
        ]
      }]);
      const getNextColumnIndex = (length) => {
            let nLength = length;
            let p = '';
            do {
              nLength--;
              const n = nLength % 26;
              p += String.fromCharCode(n + 65);
              nLength = Math.trunc((nLength - n) / 26);
            } while (nLength > 0);
            return p.split('').reverse().join('');
          };
      const gridTableTypeData = reactive([{
        name: 'sheet 1',
        r: 10,
        c: 10,
        status: 0,
        index: 0,
        order: 0,
        hide: 0,
        config: {},
        dataType: 'table',
        data: [
            [20111120001, 101, '1001', `=SUM(A1 , B1 )`, `=SUM(A1 , C1 )`, '男/女', '张三1 ', null, undefined, ''],
            [20111120002, 102, '1002', `=SUM(A2 , B2 )`, `=SUM(A2 , C2 )`, '男/女', '张三2 ', null, undefined, ''],
            [20111120003, 103, '1003', `=SUM(A3 , B3 )`, `=SUM(A3 , C3 )`, '男/女', '张三3 ', null, undefined, ''],
            [20111120004, 104, '1004', `=SUM(A4 , B4 )`, `=SUM(A4 , C4 )`, '男/女', '张三4 ', null, undefined, ''],
            [20111120005, 105, '1005', `=SUM(A5 , B5 )`, `=SUM(A5 , C5 )`, '男/女', '张三5 ', null, undefined, ''],
            [20111120006, 106, '1006', `=SUM(A6 , B6 )`, `=SUM(A6 , C6 )`, '男/女', '张三6 ', null, undefined, ''],
            [20111120007, 107, '1007', `=SUM(A7 , B7 )`, `=SUM(A7 , C7 )`, '男/女', '张三7 ', null, undefined, ''],
            [20111120008, 108, '1008', `=SUM(A8 , B8 )`, `=SUM(A8 , C8 )`, '男/女', '张三8 ', null, undefined, ''],
            [20111120009, 109, '1009', `=SUM(A9 , B9 )`, `=SUM(A9 , C9 )`, '男/女', '张三9 ', null, undefined, ''],
            [20111120010, 110, '1010', `=SUM(A10: B10)`, `=SUM(A10: C10)`, '男/女', '张三10', null, undefined, ''],
            [20111120011, 111, '1011', `=SUM(A11: B11)`, `=SUM(A11: C11)`, '男/女', '张三11', null, undefined, ''],
            [20111120012, 112, '1012', `=SUM(A12: B12)`, `=SUM(A12: C12)`, '男/女', '张三12', null, undefined, ''],
            [20111120013, 113, '1013', `=SUM(A13: B13)`, `=SUM(A13: C13)`, '男/女', '张三13', null, undefined, ''],
            [20111120014, 114, '1014', `=SUM(A14: B14)`, `=SUM(A14: C14)`, '男/女', '张三14', null, undefined, ''],
            [20111120015, 115, '1015', `=SUM(A15: B15)`, `=SUM(A15: C15)`, '男/女', '张三15', null, undefined, ''],
            [20111120016, 116, '1016', `=SUM(A16: B16)`, `=SUM(A16: C16)`, '男/女', '张三16', null, undefined, ''],
            [20111120017, 117, '1017', `=SUM(A17: B17)`, `=SUM(A17: C17)`, '男/女', '张三17', null, undefined, ''],
            [20111120018, 118, '1018', `=SUM(A18: B18)`, `=SUM(A18: C18)`, '男/女', '张三18', null, undefined, ''],
            [20111120019, 119, '1019', `=SUM(A19: B19)`, `=SUM(A19: C19)`, '男/女', '张三19', null, undefined, ''],
            [20111120020, 120, '1020', `=SUM(A20: B20)`, `=SUM(A20: C20)`, '男/女', '张三20', null, undefined, ''],
            [20111120021, 121, '1021', `=SUM(A21, B21)`, `=SUM(A21, C21)`, '男/女', '张三21', null, undefined, ''],
            [20111120022, 122, '1022', `=SUM(A22, B22)`, `=SUM(A22, C22)`, '男/女', '张三22', null, undefined, ''],
            [20111120023, 123, '1023', `=SUM(A23, B23)`, `=SUM(A23, C23)`, '男/女', '张三23', null, undefined, ''],
            [20111120024, 124, '1024', `=SUM(A24, B24)`, `=SUM(A24, C24)`, '男/女', '张三24', null, undefined, ''],
            [20111120025, 125, '1025', `=SUM(A25, B25)`, `=SUM(A25, C25)`, '男/女', '张三25', null, undefined, ''],
            [20111120026, 126, '1026', `=SUM(A26, B26)`, `=SUM(A26, C26)`, '男/女', '张三26', null, undefined, ''],
            [20111120027, 127, '1027', `=SUM(A27, B27)`, `=SUM(A27, C27)`, '男/女', '张三27', null, undefined, ''],
            [20111120028, 128, '1028', `=SUM(A28, B28)`, `=SUM(A28, C28)`, '男/女', '张三28', null, undefined, ''],
            [20111120029, 129, '1029', `=SUM(A29, B29)`, `=SUM(A29, C29)`, '男/女', '张三29', null, undefined, ''],
            [20111120030, 130, '1030', `=SUM(A30, B30)`, `=SUM(A30, C30)`, '男/女', '张三30', null, undefined, ''],
        ]
      }]);

    const gridAdvancedTableTypeData = reactive([{
        name: 'sheet 1',
        r: 10,
        c: 10,
        status: 0,
        index: 0,
        order: 0,
        hide: 0,
        config: {},
        dataType: 'table',
        data: [
            [20111120001, 101, {v: '1001', it: 1, bl: 1, bg: '#0071be', fc: '#f2f2f2',}, `=SUM(A1 , B1 )`, `=SUM(A1 , C1 )`, '男/女', '张三1 ', null, undefined, ''],
            [20111120002, 102, '1002', `=SUM(A2 , B2 )`, `=SUM(A2 , C2 )`, '男/女', '张三2 ', null, undefined, ''],
            [20111120003, 103, '1003', `=SUM(A3 , B3 )`, `=SUM(A3 , C3 )`, '男/女', '张三3 ', null, undefined, ''],
            [20111120004, 104, '1004', `=SUM(A4 , B4 )`, `=SUM(A4 , C4 )`, '男/女', '张三4 ', null, undefined, ''],
            [20111120005, 105, '1005', `=SUM(A5 , B5 )`, `=SUM(A5 , C5 )`, '男/女', '张三5 ', null, undefined, ''],
            [20111120006, 106, '1006', `=SUM(A6 , B6 )`, `=SUM(A6 , C6 )`, '男/女', '张三6 ', null, undefined, ''],
            [20111120007, 107, '1007', `=SUM(A7 , B7 )`, `=SUM(A7 , C7 )`, '男/女', '张三7 ', null, undefined, ''],
            [20111120008, 108, '1008', `=SUM(A8 , B8 )`, `=SUM(A8 , C8 )`, '男/女', '张三8 ', null, undefined, ''],
            [20111120009, 109, '1009', `=SUM(A9 , B9 )`, `=SUM(A9 , C9 )`, '男/女', '张三9 ', null, undefined, ''],
            [20111120010, 110, '1010', `=SUM(A10: B10)`, `=SUM(A10: C10)`, '男/女', '张三10', null, undefined, ''],
            [20111120011, 111, '1011', `=SUM(A11: B11)`, `=SUM(A11: C11)`, '男/女', '张三11', null, undefined, ''],
            [20111120012, 112, '1012', `=SUM(A12: B12)`, `=SUM(A12: C12)`, '男/女', '张三12', null, undefined, ''],
            [20111120013, 113, '1013', `=SUM(A13: B13)`, `=SUM(A13: C13)`, '男/女', '张三13', null, undefined, ''],
            [20111120014, 114, '1014', `=SUM(A14: B14)`, `=SUM(A14: C14)`, '男/女', '张三14', null, undefined, ''],
            [20111120015, 115, '1015', `=SUM(A15: B15)`, `=SUM(A15: C15)`, '男/女', '张三15', null, undefined, ''],
            [20111120016, 116, '1016', `=SUM(A16: B16)`, `=SUM(A16: C16)`, '男/女', '张三16', null, undefined, ''],
            [20111120017, 117, '1017', `=SUM(A17: B17)`, `=SUM(A17: C17)`, '男/女', '张三17', null, undefined, ''],
            [20111120018, 118, '1018', `=SUM(A18: B18)`, `=SUM(A18: C18)`, '男/女', '张三18', null, undefined, ''],
            [20111120019, 119, '1019', `=SUM(A19: B19)`, `=SUM(A19: C19)`, '男/女', '张三19', null, undefined, ''],
            [20111120020, 120, '1020', `=SUM(A20: B20)`, `=SUM(A20: C20)`, '男/女', '张三20', null, undefined, ''],
            [20111120021, 121, '1021', `=SUM(A21, B21)`, `=SUM(A21, C21)`, '男/女', '张三21', null, undefined, ''],
            [20111120022, 122, '1022', `=SUM(A22, B22)`, `=SUM(A22, C22)`, '男/女', '张三22', null, undefined, ''],
            [20111120023, 123, '1023', `=SUM(A23, B23)`, `=SUM(A23, C23)`, '男/女', '张三23', null, undefined, ''],
            [20111120024, 124, '1024', `=SUM(A24, B24)`, `=SUM(A24, C24)`, '男/女', '张三24', null, undefined, ''],
            [20111120025, 125, '1025', `=SUM(A25, B25)`, `=SUM(A25, C25)`, '男/女', '张三25', null, undefined, ''],
            [20111120026, 126, '1026', `=SUM(A26, B26)`, `=SUM(A26, C26)`, '男/女', '张三26', null, undefined, ''],
            [20111120027, 127, '1027', `=SUM(A27, B27)`, `=SUM(A27, C27)`, '男/女', '张三27', null, undefined, ''],
            [20111120028, 128, '1028', `=SUM(A28, B28)`, `=SUM(A28, C28)`, '男/女', '张三28', null, undefined, ''],
            [20111120029, 129, '1029', `=SUM(A29, B29)`, `=SUM(A29, C29)`, '男/女', '张三29', null, undefined, ''],
            [20111120030, 130, '1030', `=SUM(A30, B30)`, `=SUM(A30, C30)`, '男/女', '张三30', null, undefined, ''],
        ]
      }]);

      return {
        gridData,
        gridTableTypeData,
        gridAdvancedTableTypeData,
      }
    },
  })
</script>
