import { Vuepress } from '@vuepress/client'

const routeItems = [
  ["v-79fdd481","/home.html",{"title":"Project home","icon":"home"},["/home","/home.md"]],
  ["v-184f4da6","/intro.html",{"title":"Intro Page","icon":"info"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"title":"Vma-Grid","icon":"home"},["/index.html","/README.md"]],
  ["v-0e503981","/slide.html",{"title":"Slide page","icon":"slides"},["/slide","/slide.md"]],
  ["v-2f4d3eda","/basic/grid-button.html",{"title":""},["/basic/grid-button","/basic/grid-button.md"]],
  ["v-7f75cc29","/basic/grid-checkbox.html",{"title":""},["/basic/grid-checkbox","/basic/grid-checkbox.md"]],
  ["v-13863eb3","/basic/grid-icon.html",{"title":"图标"},["/basic/grid-icon","/basic/grid-icon.md"]],
  ["v-12fb0d8a","/basic/grid-loading.html",{"title":"Loading"},["/basic/grid-loading","/basic/grid-loading.md"]],
  ["v-90541d2a","/basic/grid-radio.html",{"title":""},["/basic/grid-radio","/basic/grid-radio.md"]],
  ["v-0016c312","/basic/grid-textarea.html",{"title":""},["/basic/grid-textarea","/basic/grid-textarea.md"]],
  ["v-5107b6ce","/basic/grid.html",{"title":""},["/basic/grid","/basic/grid.md"]],
  ["v-4c863446","/guide/disable.html",{"title":"Component disabled","icon":"config"},["/guide/disable","/guide/disable.md"]],
  ["v-bf720700","/guide/encrypt.html",{"title":"Encryption article","icon":"lock"},["/guide/encrypt","/guide/encrypt.md"]],
  ["v-0978b044","/guide/markdown.html",{"title":"Markdown Enhance","icon":"markdown"},["/guide/markdown","/guide/markdown.md"]],
  ["v-4eaf9f84","/guide/page.html",{"title":"page config","icon":"page"},["/guide/page","/guide/page.md"]],
  ["v-fffb8e28","/guide/",{"title":"Guides","icon":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-e0e76f98","/formula/modules.html",{"title":"vma-grid"},["/formula/modules","/formula/modules.md"]],
  ["v-1a1874fc","/formula/",{"title":"Vue 3 + Typescript + Vite"},["/formula/index.html","/formula/README.md"]],
  ["v-5a814a99","/posts/article10.html",{"title":"Article 10","icon":"edit"},["/posts/article10","/posts/article10.md"]],
  ["v-5c362338","/posts/article11.html",{"title":"Article 11","icon":"edit"},["/posts/article11","/posts/article11.md"]],
  ["v-5deafbd7","/posts/article12.html",{"title":"Article 12","icon":"edit"},["/posts/article12","/posts/article12.md"]],
  ["v-7beb5be1","/posts/article9.html",{"title":"Article 9","icon":"edit"},["/posts/article9","/posts/article9.md"]],
  ["v-bf50119c","/zh/home.html",{"title":"项目主页","icon":"home"},["/zh/home","/zh/home.md"]],
  ["v-2d0ad528","/zh/",{"title":"Vma-Grid","icon":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-998b2620","/zh/slide.html",{"title":"幻灯片页","icon":"slides"},["/zh/slide","/zh/slide.md"]],
  ["v-a9cea3dc","/formula/classes/index.DepParser.html",{"title":"Class: DepParser"},["/formula/classes/index.DepParser","/formula/classes/index.DepParser.md"]],
  ["v-44208220","/formula/classes/index.FormulaError.html",{"title":"Class: FormulaError"},["/formula/classes/index.FormulaError","/formula/classes/index.FormulaError.md"]],
  ["v-6da1d8db","/formula/classes/index.FormulaParser.html",{"title":"Class: FormulaParser"},["/formula/classes/index.FormulaParser","/formula/classes/index.FormulaParser.md"]],
  ["v-cf6e5f3c","/formula/modules/formulas.html",{"title":"Module: formulas"},["/formula/modules/formulas","/formula/modules/formulas.md"]],
  ["v-201aed0a","/formula/modules/",{"title":"Module: index"},["/formula/modules/index.html","/formula/modules/index.md"]],
  ["v-01cf4df1","/posts/article/article0.html",{"title":"Grid configuration","icon":"edit"},["/posts/article/article0","/posts/article/article0.md"]],
  ["v-03842690","/posts/article/article1.html",{"title":"Grid initialization data","icon":"edit"},["/posts/article/article1","/posts/article/article1.md"]],
  ["v-0538ff2f","/posts/article/article2.html",{"title":"Article 2","icon":"edit"},["/posts/article/article2","/posts/article/article2.md"]],
  ["v-06edd7ce","/posts/article/article3.html",{"title":"Article 3","icon":"edit"},["/posts/article/article3","/posts/article/article3.md"]],
  ["v-08a2b06d","/posts/article/article4.html",{"title":"Article 4","icon":"edit"},["/posts/article/article4","/posts/article/article4.md"]],
  ["v-0a57890c","/posts/article/article5.html",{"title":"Article 5","icon":"edit"},["/posts/article/article5","/posts/article/article5.md"]],
  ["v-0c0c61ab","/posts/article/article6.html",{"title":"Article 6","icon":"edit"},["/posts/article/article6","/posts/article/article6.md"]],
  ["v-0dc13a4a","/posts/article/article7.html",{"title":"Article 7","icon":"edit"},["/posts/article/article7","/posts/article/article7.md"]],
  ["v-0f7612e9","/posts/article/article8.html",{"title":"Article 8","icon":"edit"},["/posts/article/article8","/posts/article/article8.md"]],
  ["v-5cf61980","/posts/formula/article100.html",{"title":"概览","icon":"edit"},["/posts/formula/article100","/posts/formula/article100.md"]],
  ["v-598c6842","/posts/formula/article101.html",{"title":"数学函数","icon":"edit"},["/posts/formula/article101","/posts/formula/article101.md"]],
  ["v-5622b704","/posts/formula/article102.html",{"title":"日期函数","icon":"edit"},["/posts/formula/article102","/posts/formula/article102.md"]],
  ["v-52b905c6","/posts/formula/article103.html",{"title":"分布函数","icon":"edit"},["/posts/formula/article103","/posts/formula/article103.md"]],
  ["v-4f4f5488","/posts/formula/article104.html",{"title":"工程函数","icon":"edit"},["/posts/formula/article104","/posts/formula/article104.md"]],
  ["v-4be5a34a","/posts/formula/article105.html",{"title":"金融函数","icon":"edit"},["/posts/formula/article105","/posts/formula/article105.md"]],
  ["v-487bf20c","/posts/formula/article106.html",{"title":"信息函数","icon":"edit"},["/posts/formula/article106","/posts/formula/article106.md"]],
  ["v-451240ce","/posts/formula/article107.html",{"title":"逻辑函数","icon":"edit"},["/posts/formula/article107","/posts/formula/article107.md"]],
  ["v-41a88f90","/posts/formula/article108.html",{"title":"引用函数","icon":"edit"},["/posts/formula/article108","/posts/formula/article108.md"]],
  ["v-3e3ede52","/posts/formula/article109.html",{"title":"统计函数","icon":"edit"},["/posts/formula/article109","/posts/formula/article109.md"]],
  ["v-066b2e81","/posts/formula/article110.html",{"title":"文本函数","icon":"edit"},["/posts/formula/article110","/posts/formula/article110.md"]],
  ["v-08200720","/posts/formula/article111.html",{"title":"三角函数","icon":"edit"},["/posts/formula/article111","/posts/formula/article111.md"]],
  ["v-3f1f8b68","/zh/guide/disable.html",{"title":"组件禁用","icon":"config"},["/zh/guide/disable","/zh/guide/disable.md"]],
  ["v-b20b5e22","/zh/guide/encrypt.html",{"title":"密码加密的文章","icon":"lock"},["/zh/guide/encrypt","/zh/guide/encrypt.md"]],
  ["v-6a0a3d62","/zh/guide/markdown.html",{"title":"Markdown 增强","icon":"markdown"},["/zh/guide/markdown","/zh/guide/markdown.md"]],
  ["v-7a8fca2f","/zh/guide/page.html",{"title":"页面配置","icon":"page"},["/zh/guide/page","/zh/guide/page.md"]],
  ["v-47357bdb","/zh/guide/",{"title":"主要功能与配置演示","icon":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-fc9d8170","/zh/posts/article10.html",{"title":"文章 10","icon":"edit"},["/zh/posts/article10","/zh/posts/article10.md"]],
  ["v-f933d032","/zh/posts/article11.html",{"title":"文章 11","icon":"edit"},["/zh/posts/article11","/zh/posts/article11.md"]],
  ["v-f5ca1ef4","/zh/posts/article12.html",{"title":"文章 12","icon":"edit"},["/zh/posts/article12","/zh/posts/article12.md"]],
  ["v-4ba29552","/zh/posts/article9.html",{"title":"文章 9","icon":"edit"},["/zh/posts/article9","/zh/posts/article9.md"]],
  ["v-4d1af33c","/zh/posts/article/article0.html",{"title":"表格配置属性","icon":"edit"},["/zh/posts/article/article0","/zh/posts/article/article0.md"]],
  ["v-49b141fe","/zh/posts/article/article1.html",{"title":"表格初始化数据","icon":"edit"},["/zh/posts/article/article1","/zh/posts/article/article1.md"]],
  ["v-464790c0","/zh/posts/article/article2.html",{"title":"表格行操作功能","icon":"edit"},["/zh/posts/article/article2","/zh/posts/article/article2.md"]],
  ["v-42dddf82","/zh/posts/article/article3.html",{"title":"表格列操作功能","icon":"edit"},["/zh/posts/article/article3","/zh/posts/article/article3.md"]],
  ["v-3f742e44","/zh/posts/article/article4.html",{"title":"表格单元格操作功能","icon":"edit"},["/zh/posts/article/article4","/zh/posts/article/article4.md"]],
  ["v-3c0a7d06","/zh/posts/article/article5.html",{"title":"单元格格式","icon":"edit"},["/zh/posts/article/article5","/zh/posts/article/article5.md"]],
  ["v-38a0cbc8","/zh/posts/article/article6.html",{"title":"单元格边框、背景、颜色","icon":"edit"},["/zh/posts/article/article6","/zh/posts/article/article6.md"]],
  ["v-35371a8a","/zh/posts/article/article7.html",{"title":"文章 7","icon":"edit"},["/zh/posts/article/article7","/zh/posts/article/article7.md"]],
  ["v-31cd694c","/zh/posts/article/article8.html",{"title":"文章 8","icon":"edit"},["/zh/posts/article/article8","/zh/posts/article/article8.md"]],
  ["v-4d3bd371","/zh/posts/formula/article100.html",{"title":"概览","icon":"edit"},["/zh/posts/formula/article100","/zh/posts/formula/article100.md"]],
  ["v-4ef0ac10","/zh/posts/formula/article101.html",{"title":"数学函数","icon":"edit"},["/zh/posts/formula/article101","/zh/posts/formula/article101.md"]],
  ["v-50a584af","/zh/posts/formula/article102.html",{"title":"日期函数","icon":"edit"},["/zh/posts/formula/article102","/zh/posts/formula/article102.md"]],
  ["v-525a5d4e","/zh/posts/formula/article103.html",{"title":"分布函数","icon":"edit"},["/zh/posts/formula/article103","/zh/posts/formula/article103.md"]],
  ["v-540f35ed","/zh/posts/formula/article104.html",{"title":"工程函数","icon":"edit"},["/zh/posts/formula/article104","/zh/posts/formula/article104.md"]],
  ["v-55c40e8c","/zh/posts/formula/article105.html",{"title":"金融函数","icon":"edit"},["/zh/posts/formula/article105","/zh/posts/formula/article105.md"]],
  ["v-5778e72b","/zh/posts/formula/article106.html",{"title":"信息函数","icon":"edit"},["/zh/posts/formula/article106","/zh/posts/formula/article106.md"]],
  ["v-592dbfca","/zh/posts/formula/article107.html",{"title":"逻辑函数","icon":"edit"},["/zh/posts/formula/article107","/zh/posts/formula/article107.md"]],
  ["v-5ae29869","/zh/posts/formula/article108.html",{"title":"引用函数","icon":"edit"},["/zh/posts/formula/article108","/zh/posts/formula/article108.md"]],
  ["v-5c977108","/zh/posts/formula/article109.html",{"title":"统计函数","icon":"edit"},["/zh/posts/formula/article109","/zh/posts/formula/article109.md"]],
  ["v-fbbbe29c","/zh/posts/formula/article110.html",{"title":"文本函数","icon":"edit"},["/zh/posts/formula/article110","/zh/posts/formula/article110.md"]],
  ["v-f852315e","/zh/posts/formula/article111.html",{"title":"三角函数","icon":"edit"},["/zh/posts/formula/article111","/zh/posts/formula/article111.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]

export const pagesRoutes = routeItems.reduce(
  (result, [name, path, meta, redirects]) => {
    result.push(
      {
        name,
        path,
        component: Vuepress,
        meta,
      },
      ...redirects.map((item) => ({
        path: item,
        redirect: path,
      }))
    )
    return result
  },
  [
    {
      name: '404',
      path: '/:catchAll(.*)',
      component: Vuepress,
    }
  ]
)
