on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn run test
      - run: yarn run lib
      - run: yarn run docs:build
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: public
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: Yikun/hub-mirror-action@master
        with:
          src: github/sleiphur
          dst: gitee/sleiphur
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_style: "https"
          debug: true
          force_update: true
          static_list: "vma-grid"
          timeout: '600s'
          